version: 0.2 
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Prebuild Stage `date`
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean validate 
artifacts:

    
